# Generated by Django 5.1.4 on 2025-08-09 14:42

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150, verbose_name="Ім'я")),
                ('user_last_name', models.CharField(max_length=150, verbose_name='Прізвище')),
                ('user_phone_number', models.CharField(blank=True, max_length=13, null=True, validators=[users.models.validate_ukrainian_phone_number], verbose_name='Номер телефону')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Коментар')),
            ],
            options={
                'verbose_name': 'Клієнта',
                'verbose_name_plural': 'Клієнти',
                'db_table': 'user',
            },
        ),
    ]
