# Generated by Django 5.1.4 on 2025-08-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_options_alter_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Нове'), ('complete', 'Виконано')], db_index=True, default='in_stock', max_length=50, verbose_name='Статус'),
        ),
    ]
