# Generated by Django 5.1.4 on 2025-08-09 15:22

import goods.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_product_options_alter_product_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='photo',
            field=models.ImageField(upload_to=goods.models.product_image_upload_path, verbose_name='Зображення'),
        ),
    ]
